version: '3.1'

services:

  # Create the MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /volume1/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /volume1/docker/mosquitto/data:/mosquitto/data
      - /volume1/docker/mosquitto/log:/mosquitto/log


  #timescale DB
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: esc
      POSTGRES_PASSWORD: hKmDeqUNy4yZaJYRz7HFGQA6ns8y6sU
      POSTGRES_DB: homedb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /volume1/docker/postgresql:/var/lib/postgresql/data
  

  #Install grafaana on port 3010
  #Default username: admin
  #Default password: admin
  grafana:
    image: grafana/grafana:9.1.5
    restart: always
    ports:
      - 3010:3000
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana